python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture1.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture1.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture1.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture1.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture2.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture2.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture2.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture2.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture3.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture3.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture3.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture3.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture4.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture4.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture4.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture4.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture5.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture5.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture5.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture5.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture6.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture6.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture6.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture6.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture7.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture7.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture7.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture7.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture8.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture8.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture8.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture8.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture9.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture9.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture9.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture9.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet_15.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec_mixture10.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec_mixture10.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture10.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture10.pkl'


python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture1.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture1.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture1.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture1.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture2.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture2.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture2.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture2.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture3.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture3.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture3.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture3.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture4.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture4.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture4.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture4.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture5.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture5.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture5.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture5.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture6.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture6.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture6.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture6.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture7.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture7.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture7.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture7.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture8.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture8.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture8.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture8.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture9.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture9.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture9.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture9.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_msg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec_mixture10.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec_mixture10.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture10.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture10.pkl'


python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture1.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture1.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture1.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture1.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture2.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture2.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture2.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture2.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture3.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture3.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture3.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture3.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture4.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture4.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture4.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture4.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture5.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture5.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture5.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture5.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture6.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture6.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture6.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture6.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture7.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture7.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture7.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture7.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture8.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture8.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture8.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture8.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture9.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture9.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture9.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture9.pkl'
python get_point_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointnet2_ssg_8.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec_mixture10.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec_mixture10.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture10.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture10.pkl'


python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture1.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture1.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture1.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture1.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture2.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture2.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture2.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture2.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture3.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture3.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture3.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture3.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture4.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture4.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture4.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture4.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture5.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture5.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture5.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture5.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture6.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture6.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture6.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture6.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture7.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture7.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture7.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture7.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture8.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture8.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture8.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture8.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture9.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture9.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture9.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture9.pkl'
python get_dgcnn_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_dgcnn_6.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec_mixture10.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec_mixture10.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture10.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture10.pkl'


python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture1.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture1.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture1.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture1.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture2.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture2.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture2.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture2.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture3.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture3.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture3.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture3.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture4.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture4.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture4.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture4.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture5.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture5.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture5.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture5.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture6.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture6.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture6.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture6.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture7.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture7.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture7.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture7.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture8.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture8.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture8.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture8.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture9.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture9.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture9.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture9.pkl'
python get_pointconv_mutants_feature.py --path_target_model '/home/yinghua/pycharm/PCPrior/target_models/s3dis_pointconv_10.pt' --path_x_all_mutants '/raid/yinghua/PCPrior/pkl_data/s3dis/x_all_mutants.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --save_train_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec_mixture10.pkl' --save_test_point_mutants_feature_vec '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec_mixture10.pkl' --path_target_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture10.pkl' --path_target_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture10.pkl'




































