

python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_1.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture1.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture1.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_2.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture2.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture2.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_3.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture3.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture3.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_4.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture4.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture4.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_5.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture5.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture5.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_6.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture6.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture6.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_7.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture7.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture7.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_8.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture8.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture8.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_9.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture9.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture9.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_10.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet_15.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre_mixture10.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre_mixture10.pkl'


python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_1.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture1.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture1.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_2.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture2.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture2.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_3.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture3.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture3.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_4.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture4.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture4.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_5.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture5.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture5.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_6.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture6.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture6.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_7.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture7.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture7.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_8.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture8.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture8.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_9.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture9.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture9.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_10.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_msg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre_mixture10.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre_mixture10.pkl'


python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_1.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture1.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture1.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_2.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture2.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture2.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_3.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture3.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture3.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_4.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture4.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture4.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_5.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture5.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture5.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_6.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture6.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture6.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_7.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture7.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture7.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_8.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture8.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture8.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_9.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture9.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture9.pkl'
python get_model_pointnet_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_10.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointnet2_ssg_8.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre_mixture10.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre_mixture10.pkl'


python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_1.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture1.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture1.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_2.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture2.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture2.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_3.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture3.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture3.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_4.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture4.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture4.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_5.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture5.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture5.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_6.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture6.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture6.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_7.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture7.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture7.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_8.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture8.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture8.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_9.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture9.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture9.pkl'
python get_model_dgcnn_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_10.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_dgcnn_6.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre_mixture10.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre_mixture10.pkl'


python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_1.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture1.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture1.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_2.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture2.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture2.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_3.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture3.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture3.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_4.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture4.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture4.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_5.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture5.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture5.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_6.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture6.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture6.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_7.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture7.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture7.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_8.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture8.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture8.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_9.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture9.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture9.pkl'
python get_model_pointconv_pre.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/mixture/X_10.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl'  --model_path './target_models/s3dis_pointconv_10.pt' --save_train_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre_mixture10.pkl' --save_test_vec '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre_mixture10.pkl'




