
# retrain_dgcnn.py
python retrain_dgcnn.py --path_x '/raid/yinghua/PCPrior/pkl_data/modelnet40/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/modelnet40/y.pkl' --path_target_model '../target_models/modelnet40_dgcnn_2.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_dgcnn_2_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_dgcnn_2_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/dgcnn_2_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/dgcnn_2_test_point_mutants_feature_vec.pkl' --path_save './result/modelnet40_dgcnn_2.json'
python retrain_dgcnn.py --path_x '/raid/yinghua/PCPrior/pkl_data/shapenet/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/shapenet/y.pkl' --path_target_model '../target_models/shapenet_dgcnn_0.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_dgcnn_0_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_dgcnn_0_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/dgcnn_0_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/dgcnn_0_test_point_mutants_feature_vec.pkl' --path_save './result/shapenet_dgcnn_0.json'
python retrain_dgcnn.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --path_target_model '../target_models/s3dis_dgcnn_6.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_dgcnn_6_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/dgcnn_6_test_point_mutants_feature_vec.pkl' --path_save './result/s3dis_dgcnn_6.json'


# retrain_pointnet_cls.py
python retrain_pointnet_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/modelnet40/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/modelnet40/y.pkl' --path_target_model '../target_models/modelnet40_pointnet_2.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointnet_2_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointnet_2_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointnet_2_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointnet_2_test_point_mutants_feature_vec.pkl' --path_save './result/modelnet40_pointnet_2.json'
python retrain_pointnet_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/shapenet/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/shapenet/y.pkl' --path_target_model '../target_models/shapenet_pointnet_0.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointnet_0_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointnet_0_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointnet_0_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointnet_0_test_point_mutants_feature_vec.pkl' --path_save './result/shapenet_pointnet_0.json'
python retrain_pointnet_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --path_target_model '../target_models/s3dis_pointnet_15.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet_15_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet_15_test_point_mutants_feature_vec.pkl' --path_save './result/s3dis_pointnet_15.json'


# retrain_pointnet2_msg_cls.py
python retrain_pointnet2_msg_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/modelnet40/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/modelnet40/y.pkl' --path_target_model '../target_models/modelnet40_pointnet2_msg_2.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointnet2_msg_2_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointnet2_msg_2_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointnet2_msg_2_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointnet2_msg_2_test_point_mutants_feature_vec.pkl' --path_save './result/modelnet40_pointnet2_msg_2.json'
python retrain_pointnet2_msg_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/shapenet/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/shapenet/y.pkl' --path_target_model '../target_models/shapenet_pointnet2_msg_0.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointnet2_msg_0_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointnet2_msg_0_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointnet2_msg_0_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointnet2_msg_0_test_point_mutants_feature_vec.pkl' --path_save './result/shapenet_pointnet2_msg_0.json'
python retrain_pointnet2_msg_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --path_target_model '../target_models/s3dis_pointnet2_msg_8.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_msg_8_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_msg_8_test_point_mutants_feature_vec.pkl' --path_save './result/s3dis_pointnet2_msg_8.json'


# retrain_pointnet2_ssg_cls.py
python retrain_pointnet2_ssg_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/modelnet40/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/modelnet40/y.pkl' --path_target_model '../target_models/modelnet40_pointnet2_ssg_2.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointnet2_ssg_2_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointnet2_ssg_2_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointnet2_ssg_2_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointnet2_ssg_2_test_point_mutants_feature_vec.pkl' --path_save './result/modelnet40_pointnet2_ssg_2.json'
python retrain_pointnet2_ssg_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/shapenet/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/shapenet/y.pkl' --path_target_model '../target_models/shapenet_pointnet2_ssg_0.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointnet2_ssg_0_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointnet2_ssg_0_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointnet2_ssg_0_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointnet2_ssg_0_test_point_mutants_feature_vec.pkl' --path_save './result/shapenet_pointnet2_ssg_0.json'
python retrain_pointnet2_ssg_cls.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --path_target_model '../target_models/s3dis_pointnet2_ssg_8.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointnet2_ssg_8_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointnet2_ssg_8_test_point_mutants_feature_vec.pkl' --path_save './result/s3dis_pointnet2_ssg_8.json'


# retrain_pointconv.py
#python retrain_pointconv.py --path_x '/raid/yinghua/PCPrior/pkl_data/modelnet40/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/modelnet40/y.pkl' --path_target_model '../target_models/modelnet40_pointconv_8.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointconv_8_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/modelnet40_pre/modelnet40_pre_pointconv_8_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointconv_8_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/modelnet40/pointconv_8_test_point_mutants_feature_vec.pkl' --path_save './result/modelnet40_pointconv_8.json'
#python retrain_pointconv.py --path_x '/raid/yinghua/PCPrior/pkl_data/shapenet/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/shapenet/y.pkl' --path_target_model '../target_models/shapenet_pointconv_2.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointconv_2_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/shapenet_pre/shapenet_pre_pointconv_2_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointconv_2_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/shapenet/pointconv_2_test_point_mutants_feature_vec.pkl' --path_save './result/shapenet_pointconv_2.json'
#python retrain_pointconv.py --path_x '/raid/yinghua/PCPrior/pkl_data/s3dis/X.pkl' --path_y '/raid/yinghua/PCPrior/pkl_data/s3dis/y.pkl' --path_target_model '../target_models/s3dis_pointconv_10.pt' --path_target_model_train_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_train_pre.pkl' --path_target_model_test_pre '/raid/yinghua/PCPrior/pkl_data/s3dis_pre/s3dis_pre_pointconv_10_test_pre.pkl' --path_train_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_train_point_mutants_feature_vec.pkl' --path_test_point_mutants_feature '/raid/yinghua/PCPrior/pkl_data/s3dis/pointconv_10_test_point_mutants_feature_vec.pkl' --path_save './result/s3dis_pointconv_10.json'
